const fs = require('fs');
const path = 'c:\\\\Users\\\\rushi\\\\Downloads\\\\DCneetcounselling\\\\frontend\\\\web\\\\index.html';
let content = fs.readFileSync(path, 'utf8');

// 1. Update the "Starts from" labels safely by matching the context
content = content.replace(/<h3 class="ec-title">Medical<\/h3>\s*<p class="ec-courses">MBBS<\/p>\s*<div class="ec-price">\s*<i class="fas fa-tag"><\/i> Starts from ₹1/g, '<h3 class="ec-title">Medical</h3>\\n              <p class="ec-courses">MBBS</p>\\n              <div class="ec-price">\\n                <i class="fas fa-tag"></i> Starts from ₹99');
content = content.replace(/<h3 class="ec-title">Dental<\/h3>\s*<p class="ec-courses">BDS<\/p>\s*<div class="ec-price">\s*<i class="fas fa-tag"><\/i> Starts from ₹1/g, '<h3 class="ec-title">Dental</h3>\\n              <p class="ec-courses">BDS</p>\\n              <div class="ec-price">\\n                <i class="fas fa-tag"></i> Starts from ₹149');
content = content.replace(/<h3 class="ec-title">AYUSH<\/h3>\s*<p class="ec-courses">BAMS, BHMS, BSMS, BUMS<\/p>\s*<div class="ec-price">\s*<i class="fas fa-tag"><\/i> Starts from ₹1/g, '<h3 class="ec-title">AYUSH</h3>\\n              <p class="ec-courses">BAMS, BHMS, BSMS, BUMS</p>\\n              <div class="ec-price">\\n                <i class="fas fa-tag"></i> Starts from ₹199');
content = content.replace(/<h3 class="ec-title">Veterinary<\/h3>\s*<p class="ec-courses">BVSc<\/p>\s*<div class="ec-price">\s*<i class="fas fa-tag"><\/i> Starts from ₹1/g, '<h3 class="ec-title">Veterinary</h3>\\n              <p class="ec-courses">BVSc</p>\\n              <div class="ec-price">\\n                <i class="fas fa-tag"></i> Starts from ₹149');

content = content.replace(/<div class="mo-card scale-up" onclick="openEbookPurchaseModal\('Medical', 'All India Quota', 1, 'Medical AIQ eBooks'\)">\s*<div class="mo-highlight" style="background: rgba\(37,99,235,0\.1\); color: #2563eb; margin-bottom: 12px;">\s*<i class="fas fa-star"><\/i> Most Popular\s*<\/div>\s*<div class="mo-icon" style="color: #2563eb;">\s*<i class="fas fa-globe-asia"><\/i>\s*<\/div>\s*<h4 class="mo-title">All India Quota<\/h4>\s*<div class="mo-price">\s*<i class="fas fa-tag"><\/i> Starts from ₹1/g, '<div class="mo-card scale-up" onclick="openEbookPurchaseModal(\\'Medical\\', \\'All India Quota\\', 199, \\'Medical AIQ eBooks\\')">\\n                <div class="mo-highlight" style="background: rgba(37,99,235,0.1); color: #2563eb; margin-bottom: 12px;">\\n                  <i class="fas fa-star"></i> Most Popular\\n                </div>\\n                <div class="mo-icon" style="color: #2563eb;">\\n                  <i class="fas fa-globe-asia"></i>\\n                </div>\\n                <h4 class="mo-title">All India Quota</h4>\\n                <div class="mo-price">\\n                  <i class="fas fa-tag"></i> Starts from ₹199');

content = content.replace(/<div class="mo-card scale-up" onclick="openEbookPurchaseModal\('Medical', 'State Quota', 1, 'Medical State Quota eBooks'\)">\s*<div class="mo-icon" style="color: #16a34a;">\s*<i class="fas fa-map-marker-alt"><\/i>\s*<\/div>\s*<h4 class="mo-title">State Quota<\/h4>\s*<p style="font-size: 13px; color: #64748b; margin-bottom: 15px;">State-wise detailed cutoff analysis<\/p>\s*<div class="mo-price">\s*<i class="fas fa-tag"><\/i> Starts from ₹1/g, '<div class="mo-card scale-up" onclick="openEbookPurchaseModal(\\'Medical\\', \\'State Quota\\', 99, \\'Medical State Quota eBooks\\')">\\n                <div class="mo-icon" style="color: #16a34a;">\\n                  <i class="fas fa-map-marker-alt"></i>\\n                </div>\\n                <h4 class="mo-title">State Quota</h4>\\n                <p style="font-size: 13px; color: #64748b; margin-bottom: 15px;">State-wise detailed cutoff analysis</p>\\n                <div class="mo-price">\\n                  <i class="fas fa-tag"></i> Starts from ₹99');

// 2. Update the modal calls (buttons)
content = content.replace(/openEbookPurchaseModal\('Dental', 'All Courses', 1, 'Dental Cutoff eBooks'\)/g, "openEbookPurchaseModal('Dental', 'All Courses', 149, 'Dental Cutoff eBooks')");
content = content.replace(/openEbookPurchaseModal\('AYUSH', 'All Courses', 1, 'AYUSH Cutoff eBooks'\)/g, "openEbookPurchaseModal('AYUSH', 'All Courses', 199, 'AYUSH Cutoff eBooks')");
content = content.replace(/openEbookPurchaseModal\('Veterinary', 'All Courses', 1, 'Veterinary Cutoff eBooks'\)/g, "openEbookPurchaseModal('Veterinary', 'All Courses', 149, 'Veterinary Cutoff eBooks')");
content = content.replace(/openEbookPurchaseModal\('Medical', 'All India Quota', 1, 'Medical AIQ eBooks'\)/g, "openEbookPurchaseModal('Medical', 'All India Quota', 199, 'Medical AIQ eBooks')");
content = content.replace(/openEbookPurchaseModal\('Medical', 'State Quota', 1, 'Medical State Quota eBooks'\)/g, "openEbookPurchaseModal('Medical', 'State Quota', 99, 'Medical State Quota eBooks')");

// 3. Update EBOOK_META
content = content.replace(/'medical': { title: 'Medical', icon: 'fa-stethoscope', color: '#2563eb', price: 1, courses: 'MBBS'/g, "'medical': { title: 'Medical', icon: 'fa-stethoscope', color: '#2563eb', price: 99, courses: 'MBBS'");
content = content.replace(/'dental': { title: 'Dental', icon: 'fa-tooth', color: '#06b6d4', price: 1, courses: 'BDS'/g, "'dental': { title: 'Dental', icon: 'fa-tooth', color: '#06b6d4', price: 149, courses: 'BDS'");
content = content.replace(/'ayush': { title: 'AYUSH', icon: 'fa-leaf', color: '#16a34a', price: 1, courses: 'BAMS, BHMS, BSMS, BUMS'/g, "'ayush': { title: 'AYUSH', icon: 'fa-leaf', color: '#16a34a', price: 199, courses: 'BAMS, BHMS, BSMS, BUMS'");
content = content.replace(/'veterinary': { title: 'Veterinary', icon: 'fa-paw', color: '#f59e0b', price: 1, courses: 'BVSc'/g, "'veterinary': { title: 'Veterinary', icon: 'fa-paw', color: '#f59e0b', price: 149, courses: 'BVSc'");

fs.writeFileSync(path, content, 'utf8');
console.log("Prices successfully updated!");
